os:
- linux
services:
- docker
language: node_js
node_js:
- 8.9.4
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
  - "$HOME/.yarn-cache"
env:
  global:
  - NODE_VERSION=8.9.4
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
before_install:
- jdk_switcher use oraclejdk8
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn install
script:
- chmod +x mvnw
- "./mvnw clean test"
- yarn test
- "./mvnw verify -Pprod -DskipTests"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
deploy:
- provider: s3
  access_key_id: AKIAJRFDHQNWDWAGVM7Q
  secret_access_key: &1
    secure: HpRIHb7KrZjBwWfAc35y0C6w7WMb9F+y7POFBX3SKueY1nXam+mE3vyvgtAB2pc8g1kFvBPbx5ziAxxZSKoglVcE1DLbihhRtDLzPQEYzw3B4oSv1s0Ws57j921KQ61GU6yEnNfTUSvLn4W9ffy3dDM/SdNxomJjFENbltXcgMpxskZeb/GerWKDRnVrN8UFqU3/TwEhkdRLCZ4nhs57I80V2hsthGZVpiKm38jPgnIw9nWiJtZATVpopKRUsiFLkKDNCbYcKunqLqZZ8xobeXLd9JM1T/xxw1g0X0C1oFfXUeC189ArwRBO7coT4JknratAd4hPyBeqt+o6SsnQWjBX6j42oKnWXhAnHI/149gcD+KX41Bfm6mEhNv/D7caOCDK4febmHtO5MVogdailLA5vqnkfblgAA0kFCP0kbmn/bRR0TKa1hsLfZvRF9IhmfsisK/d2FjtgN7cONJ5wpZtZBrLQEc8N2vLyMZZP3Lm5GbM+QygF/1MyBGHXLiH6BE3Q513mM/kIjKWt4eqY247jLYyHbCRv4MCzfqAJnfSBzPJyWAnOoG+3ztn8C7jaY0cRFCL3f3csQ3ZDvv69IgEMGWic3Io+5uy3KlmKuP0xHvvAXHHldzgfZ9rWegmvQUz0puYYXhrpnnLJCE1+dJ8QVB+1ho38MKiXA5sn5g=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: adhawan-vip/vip_adpq
  bucket: vip-adpq
- provider: codedeploy
  access_key_id: AKIAJRFDHQNWDWAGVM7Q
  secret_access_key: *1
  bucket: vip-adpq
  key: vip-adpq-app
  bundle_type: ''
  application: vip_adpq
  deployment_group: ''
  on: *2
before_deploy:
- mkdir -p dpl_cd_upload
- mv vip-adpq-app dpl_cd_upload/vip-adpq-app
