version: '2'
services:
    vip_adpq-app:
        image: vip_adpq
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://vip_adpq-mysql:3306/vip_adpq?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    vip_adpq-mysql:
        extends:
            file: mysql.yml
            service: vip_adpq-mysql
